packages:
  - packages/typescript-config
  - packages/chains
  - packages/explorers
  - packages/providers
  - packages/query
  - packages/react
  # - packages/vue
  - docs

onlyBuiltDependencies:
  - esbuild
